apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: sales-api
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"

          volumeMounts:
            - name: vault
              mountPath: /vault

        - name: metrics
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
